services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      <<: *db-env
      BASE_URL: https://supreme-telegram-q7pxpjqxp472xx6r-3000.app.github.dev
      SECRET_KEY_BASE: secretkeybasehere
    ports:
      - "3000:3000"