default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['MYSQL_PORT'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DB'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DB'] %>_test
  
production:
  <<: *default
  database: <%= ENV['MYSQL_DB'] %>